image: node:latest

stages:
  - lint

eslint:
  stage: lint
  before_script:
  - npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
  script:
  - npx eslint .
  tags:
  - docker 
