image: node:latest

stages:
  - lint
  - test

eslint:
  stage: lint
  before_script:
  - npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
  script:
  - npx eslint .
  tags:
  - docker

unit-tests:
  stage: test
  before_script:
  - npm install mocha
  script: 
  - ./node_modules/mocha/bin/mocha --recursive \"test/\"
  tags:
  - docker
