image: node:latest

stages:
  - lint
  - deploy

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
  tags:
  - docker

eslint:
  stage: lint
  before_script:
  - npm install --save-dev eslint eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
  script:
  - npx eslint scripts/
  tags:
  - docker 
