{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-recommended-scss"
  ],
  "plugins": [
    "stylelint-scss"
  ],
  "rules": {
    "indentation": [ 2, {
      "except": ["block"],
      "message": "Please use 2 spaces for indentation.",
      "severity": "warning"
    } ],
    "max-empty-lines": 2,
    "rule-empty-line-before": [ "always", {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    } ],
    "unit-whitelist": ["em", "rem", "%", "s"]
  }
}